const TipoTerapia = {
    AVDS: "A.V.D.S",
    CASA_ADAPTADA: "Casa adaptada",
    COMUNICACAO_ALTERNATIVA: "Comunicacao alternativa/suplementar",
    DISFAGIA: "Disfagia",
    ESTIMULACAO_AUDITIVA: "Estimulação auditiva",
    ESTIMULACAO_VISUAL: "Estimulação visual",
    FISIOTERAPIA: "Fisioterapia",
    FISIOTERAPIA_MOTORA: "Fisioterapia motora",
    FISIOTERAPIA_RESPIRATORIA: "Fisioterapia respiratória",
    FONOAUDIOLOGIA: "Fonoaudiologia",
    FORTALECIMENTO: "Fortalecimento",
    GAME: "Game",
    GESTAO_COMPORTAMENTO: "Gestão de Comportamento",
    GRUPO_T21: "Grupo de T21",
    HABILIDADES_SOCIAIS: "Habilidades Sociais",
    INTERDISCIPLINAR: "Interdisciplinar",
    INTERMEDIARIO: "Intermediário",
    MOTRICIDADE: "Motricidade",
    MULTIPROFISSIONAL_I_II: "Multiprofissional I e II",
    MULTIPROFISSIONAL_III: "Multiprofissional III",
    MULTIPROFISSIONAL_V: "Multiprofissional V",
    MUSICOTERAPIA: "Musicoterapia",
    OUTROS: "Outros",
    PROJETO_QUATRO_ESTACOES: "Projeto quatro estações",
    PSICOLOGIA: "Psicologia",
    PSICOMOTRICIDADE: "Psicomotricidade",
    REABILITACAO_AUDITIVA: "Reabilitação auditiva",
    REABILITACAO_FALA_LINGUAGEM: "Reabilitação de Fala e linguagem",
    REABILITACAO_INTELECTUAL: "Reabilitação intelectual",
    ROBOTICA: "Robótica",
    SELETIVIDADE_ALIMENTAR: "Seletividade Alimentar",
    TERAPIA_OCUPACIONAL: "Terapia ocupacional",
    TREINAMENTO_BIMANUAL: "Treinamento bimanual"
};

export default TipoTerapia;