const DoencasPreExistentesMae = {
    ALERGIA_ALIMENTAR: "Alergia alimentar",
    ALERGIA_MEDICAMENTOSA: "Alergia medicamentosa",
    ALERGIA_OCULAR: "Alergia ocular",
    ASMA_ALERGICA: "Asma alérgica",
    DERMATITE_ALERGICA: "Dermatite alérgica",
    RINITE_ALERGICA: "Rinite alérgica",

    AUTOIMUNE_ANEMIA_HEMOLITICA: "Autoimune - Anemia hemolítica",
    AUTOIMUNE_ARTRITE_REUMATOIDE: "Autoimune - Artrite reumatóide",
    AUTOIMUNE_DIABETES_TIPO_1: "Autoimune - Diabetes tipo 1",
    AUTOIMUNE_DOENCA_CELIACA: "Autoimune - Doença celíaca",
    AUTOIMUNE_ESCLEROSE_MULTIPLA: "Autoimune - Esclerose múltipla",
    AUTOIMUNE_LUPUS: "Autoimune - Lupus eritematoso sistêmico",
    AUTOIMUNE_SJOGREN: "Autoimune - Síndrome de Sjögren",
    AUTOIMUNE_HASHIMOTO: "Autoimune - Tireóide de Hashimoto",
    AUTOIMUNE_VITILIGO: "Autoimune - Vitiligo",

    CARDIOPATIA_ANGINA: "Cardiopatias - Angina",
    CARDIOPATIA_ANOMALIA_EBSTEIN: "Cardiopatias - Anomalia de Ebstein",
    CARDIOPATIA_ARRITMIA: "Cardiopatias - Arritmia",
    CARDIOPATIA_ATRESIA_PULMONAR: "Cardiopatias - Atresia pulmonar",
    CARDIOPATIA_COMUNICACAO_INTERATRIAL: "Cardiopatias - Comunicação interatrial",
    CARDIOPATIA_COMUNICACAO_INTERVENTRICULAR: "Cardiopatias - Comunicação interventricular",
    CARDIOPATIA_DEFEITO_SEPTO_ATRIOVENTRICULAR: "Cardiopatias - Defeito no septo atrioventricular",
    CARDIOPATIA_ENDOCARDITE: "Cardiopatias - Encocardite",
    CARDIOPATIA_INFARTO: "Cardiopatias - Infarto",
    CARDIOPATIA_INSUFICIENCIA_CARDIACA: "Cardiopatias - Insuficiência cardíaca",
    CARDIOPATIA_MIOCARDITE: "Cardiopatias - Miocardite",
    CARDIOPATIA_PERICARDITE: "Cardiopatias - Pericardite",
    CARDIOPATIA_PERSISTENCIA_CANAL_ARTERIAL: "Cardiopatias - Persistência do canal arterial",
    CARDIOPATIA_TETRALOGIA_FALLOT: "Cardiopatias - tetralogia de Fallot",
    CARDIOPATIA_TRANSPOSICAO_GRANDES_VASOS: "Cardiopatias - transposição dos grandes vasos da base",
    CARDIOPATIA_VALVULOPATIA: "Cardiopatias - valvulopatia",

    DISTURBIO_COAGULACAO_CID: "Distúrbio de coagulação - Coagulação intravascular disseminada",
    DISTURBIO_COAGULACAO_DEFICIENCIA_ALFA2: "Distúrbio de coagulação - Deficiência de alfa 2-antiplasmina",
    DISTURBIO_COAGULACAO_DEFICIENCIA_FATOR_II: "Distúrbio de coagulação - Deficiência do fator II",
    DISTURBIO_COAGULACAO_DEFICIENCIA_FATOR_V: "Distúrbio de coagulação - Deficiência do fator V",
    DISTURBIO_COAGULACAO_DEFICIENCIA_FATOR_VII: "Distúrbio de coagulação - Deficiência do fator VII",
    DISTURBIO_COAGULACAO_DEFICIENCIA_FATOR_X: "Distúrbio de coagulação - Deficiência do fator X",
    DISTURBIO_COAGULACAO_DEFICIENCIA_FATOR_XI: "Distúrbio de coagulação - Deficiência do fator XI",
    DISTURBIO_COAGULACAO_HEMOFILIA: "Distúrbio de coagulação - Hemofilia / Doença de von Willebrand",
    DISTURBIO_COAGULACAO_TROMBOCITOPENIA: "Distúrbio de coagulação - Trombocitopenia",

    DOENCA_PSIQUIATRICA_ESQUIZOFRENIA: "Doenças psiquiátricas - Esquizofrenia",
    DOENCA_PSIQUIATRICA_PSICOSE_MANIACO_DEPRESSIVA: "Doenças psiquiátricas - Psicose maníaco depressiva",
    DOENCA_PSIQUIATRICA_PSICOSE_OBSESSIVA_COMPULSIVA: "Doenças psiquiátricas - Psicose obsessiva compulsiva",
    DOENCA_PSIQUIATRICA_BORDERLINE: "Doenças psiquiátricas - Transtorno borderline",
    DOENCA_PSIQUIATRICA_ANSIEDADE_GENERALIZADA: "Doenças psiquiátricas - Transtorno de ansiedade generalizada",
    DOENCA_PSIQUIATRICA_DISSOCIATIVO: "Doenças psiquiátricas - Transtorno dissociativo",
    DOENCA_PSIQUIATRICA_PANICO: "Doenças psiquiátricas - Transtorno do pânico",

    NENHUMA: "Nenhuma",
    OUTROS: "Outros",
    SI: "SI"
};

export default DoencasPreExistentesMae;