const ExamesRealizadosMae = {
    AMNIOCENTESE_ALTERADO: "Amniocentese - Alterado",
    AMNIOCENTESE_NORMAL: "Amniocentese - Normal",
    BIOPSIA_CARIOTIPO_FETAL_ALTERADO: "Biópsia cariótipo fetal - Alterado",
    BIOPSIA_CARIOTIPO_FETAL_NORMAL: "Biópsia cariótipo fetal - Normal",
    BIOPSIA_VILO_CORIAL_ALTERADO: "Biópsia do vilo corial - Alterado",
    BIOPSIA_VILO_CORIAL_NORMAL: "Biópsia do vilo corial - Normal",
    CARDIOTOCOGRAFIA_ALTERADO: "Cardiotocografia - Alterado",
    CARDIOTOCOGRAFIA_NORMAL: "Cardiotocografia - Normal",
    CORDOCENTESE_ALTERADO: "Cordocentese - Alterado",
    CORDOCENTESE_NORMAL: "Cordocentese - Normal",
    ECOCARDIOGRAMA_FETAL_NORMAL: "Ecocardiograma fetal - Normal",
    ELETROCARDIOGRAMA_FETAL_ALTERADO: "Eletrocardiograma fetal - Alterado",
    GLICOSE_JEJUM_ALTERADO: "Glicose em jejum - Alterado",
    GLICOSE_JEJUM_NORMAL: "Glicose em jejum - Normal",
    HEMOGRAMA_ALTERADO: "Hemograma - Alterado",
    HEMOGRAMA_NORMAL: "Hemograma - Normal",
    HIV_ALTERADO: "HIV - Alterado",
    HIV_NORMAL: "HIV - Normal",
    MAPA_ALTERADO: "MAPA - Alterado",
    MAPA_NORMAL: "MAPA - Normal",
    PERFIL_BIOQUIMICO_FETAL_ALTERADO: "Perfil bioquímico fetal - Alterado",
    PERFIL_BIOQUIMICO_FETAL_NORMAL: "Perfil bioquímico fetal - Normal",
    TIPO_SANGUINEO_FATOR_RH_ALTERADO: "Tipo sanguíneo e fator RH - Alterado",
    TIPO_SANGUINEO_FATOR_RH_NORMAL: "Tipo sanguíneo e fator RH - Normal",
    TORCH_ALTERADO: "TORCH - Alterado",
    TORCH_NORMAL: "TORCH - Normal",
    VDRL_ALTERADO: "VDRL - Alterado",
    VDRL_NORMAL: "VDRL - Normal",
    NENHUM: "Nenhum",
    OUTROS: "Outros",
    SI: "SI"
};

export default ExamesRealizadosMae;