const MotivoHospitalizacao = {
    ACIDENTE_TRABALHO_MATERIAL_BIOLOGICO: "Acidente de trabalho com exposição a material biológico",
    ACIDENTE_ANIMAL_PECONHENTO: "Acidente por animal peçonhento",
    ACIDENTE_ANIMAL_RAIVA: "Acidente por animal potencialmente transmissor da raiva",
    ALOIMUNIZACAO: "Aloimunização",
    AMNIORREXE_PREMATURA: "Amniorrexe prematura",
    ANEMIA: "Anemia",
    ANTRAZ: "Antraz",
    APENDICITE: "Apendicite",
    ARTRITE_TAKAYASU: "Artrite de Takayasu",
    ARTRITE_REUMATOIDE: "Artrite reumatoide",
    ARTROSE_GENERALIZADA_SEVERA: "Artrose Generalizada Severa",
    ASMA: "Asma",
    ATELECTASIA: "Atelectasia",
    BOTULISMO: "Botulismo",
    BRONQUITE: "Bronquite",
    CANCER_TIREOIDE: "Câncer da tireoide",
    CANCER_TUBA_UTERINA: "Câncer da tuba uterina",
    CANCER_COLO_UTERO: "Câncer de colo de útero",
    CANCER_MAMA: "Câncer de mama",
    CANCER_VAGINA: "Câncer de vagina",
    CANCER_VULVA: "Câncer de vulva",
    CANCER_ENDOMETRIO: "Câncer do endométrio",
    CANCER_OVARIO: "Câncer do ovário",
    CARDIOPATIA: "Cardiopatia",
    CATAPORA: "Catapora",
    CHIKUNGUNYA: "Chikungunha",
    CISTOCELE: "Cistocele",
    CONVULSAO: "Convulsão",
    DENGUE: "Dengue",
    DIABETES_INSIPIDUS: "Diabetes insipidus",
    DIABETES_GESTACIONAL: "Diabetes mellitus gestacional (DMG)",
    DISTONIA_SEGMENTADA: "Distonia segmentada",
    DISTURBIOS_TIREOIDE: "Distúrbios da tireoide",
    DOENCA_AUTOIMUNE: "Doença auto imune",
    DOENCA_CHAGAS: "Doença de Chagas",
    DOENCA_CHARCOT_MARIE_TOOTH: "Doença de Charcot-Marie-Tooth",
    DOENCA_CREUTZFELDT_JAKOB: "Doença de Creutzfeldt-Jakob (DCJ)",
    DOENCA_HUNTINGTON: "Doença de Huntington",
    DOENCA_HAEMOPHILUS_INFLUENZA: "Doença Invasiva por Haemophilus Influenza",
    DOENCA_MENINGOCOCICA: "Doença Meningocócica e outras meningites",
    ECLAMPSIA: "Eclâmpsia",
    EDEMA_PULMONAR: "Edema pulmonar",
    EMBOLIA_GASOSA: "Embolia gasosa",
    EMBOLIA_PULMONAR: "Embolia pulmonar",
    ENDOMETRIOSE: "Endometriose",
    EPILEPSIA: "Epilepsia",
    ESCLEROSE_MULTIPLA: "Esclerose múltipla",
    ESQUISTOSSOMOSE: "Esquistossomose",
    FEBRE_NILO: "Febre do Nilo Ocidental e outras arboviroses",
    FEBRE_MACULOSA: "Febre Maculosa e outras Riquetisioses",
    FEBRE_TIFOIDE: "Febre tifoide",
    FRATURA: "Fratura",
    GASTRITE: "Gastrite",
    GLIOMA: "Glioma",
    HANSENIASE: "Hanseníase",
    HANTAVIROSE: "Hantavirose",
    HEMOFILIA: "Hemofilia",
    HEMORRAGIAS_GESTACAO: "Hemorragias da gestação",
    HEMORROIDA: "Hemorroida",
    HEMOSSIDEROSE_PULMONAR: "Hemossiderose pulmonar",
    HEPATITE_A: "Hepatite A",
    HEPATITE_B: "Hepatite B",
    HEPATITE_C: "Hepatite C",
    HERPES: "Herpes",
    HERPES_GENITAL: "Herpes genital",
    HIPEREMESE: "Hiperêmese",
    HIPERTENSAO_CRONICA: "Hipertensão crônica",
    HIPERTENSAO_GESTACIONAL: "Hipertensão gestacional",
    HIPOTIREOIDISMO: "Hipotireoidismo",
    HIV_AIDS: "HIV/AIDS - Infecção pelo Vírus da Imunodeficiência Humana ou Síndrome da Imunodeficiência Adquirida",
    INFARTO_AGUDO_MIOCARDIO: "Infarto agudo do miocárdio",
    INFECCAO_HIV_GESTANTE: "Infecção pelo HIV em gestante, parturiente ou puérpera e Criança exposta ao risco de transmissão vertical do HIV",
    INFECCAO_URINARIA: "Infecção urinária",
    INFLUENZA: "Influenza humana produzida por novo subtipo viral",
    INSUFICIENCIA_ISTMO_CERVICAL: "Insuficiência istmo-cervical",
    INSUFICIENCIA_RENAL_AGUDA: "Insuficiência renal aguda",
    INSUFICIENCIA_RENAL_CRONICA: "Insuficiência renal crônica",
    INTOXICACAO_EXOGENA: "Intoxicação Exógena (por substâncias químicas, incluindo agrotóxicos, gases tóxicos e metais pesados)",
    LEISHMANIOSE_TEGUMENTAR: "Leishmaniose tegumentar americana",
    LEISHMANIOSE_VISCERAL: "Leishmaniose Visceral",
    LEPTOSPIROSE: "Leptospirose",
    LEUCEMIA: "Leucemia",
    LUPUS: "Lúpus eritematoso sistêmico",
    MALARIA_AMAZONICA: "Malária na região amazônica",
    MALARIA_EXTRA_AMAZONICA: "Malária na região extra-Amazônica",
    MELANOMA: "Melanoma",
    MENINGITE: "Meningite",
    NEFROPATIA: "Nefropatia",
    NEOPLASIA_TROFOBLASTICA: "Neoplasia trofoblástica gestacional",
    PANCREATITE: "Pancreatite",
    PARKINSON: "Parkinson",
    PERIODONTITE: "Periodontite",
    PLACENTA_PREVIA: "Placenta prévia",
    PNEUMONIA: "Pneumonia",
    POLIOMIELITE: "Poliomielite",
    PRE_ECLAMPSIA: "Pré eclâmpsia",
    PROLAPSO_UTERINO: "Prolapso uterino",
    RAIVA: "Raiva",
    RETOCELE: "Retocele",
    RUBEOLA: "Rubéola e síndrome da rubéola congênita",
    SARAMPO: "Sarampo",
    SEPTICEMIA: "Septicemia",
    SIFILIS: "Sífilis",
    SINDROME_PFA: "Síndrome da Paralisia Flácida Aguda",
    SINDROME_GUILLAIN_BARRE: "Síndrome de Guillain Barré",
    SINDROME_HELLP: "Síndrome de HELLP",
    SINDROME_COVID: "Síndrome Respiratória Aguda Grave associada a Coronavírus",
    TETANO: "Tétano",
    TIREOIDE_HASHIMOTO: "Tireoide de Hashimoto",
    TOXOPLASMOSE: "Toxoplasmose gestacional e congênita",
    TROMBOEMBOLISMO: "Tromboembolismo",
    TROMBOFILIA: "Trombofilia",
    TUBERCULOSE: "Tuberculose",
    TULAREMIA: "Tularemia",
    UTEROCELE: "Uterocele",
    VAGINOSE_BACTERIANA: "Vaginose bacteriana",
    VARICELA: "Varicela",
    VARIOLA: "Varíola",
    VASCULOPATIA: "Vasculopatia",
    VIOLENCIA_DOMESTICA: "Violência doméstica e/ou outras violências",
    VIOLENCIA_SEXUAL: "Violência sexual e tentativa de suicídio",
    ZIKA: "Zika",
    OUTRO: "Outro",
    SI: "SI"
  };

  export default MotivoHospitalizacao;