const Antibiotico = {
    ACIDO_CLAVULANICO: "Ácido clavulânico",
    ACIDO_FUSIDICO: "Ácido fusídico",
    ACIDO_NALIDIXICO: "Ácido nalidíxico",
    ACIDO_OXOLINICO: "Ácido oxolínico",
    ACIDO_PIPEMIDICO: "Ácido pipemídico",
    AMICACINA: "Amicacina",
    AMOXICILINA: "Amoxicilina",
    AMPICILINA: "Ampicilina",
    AXETILCEFUROXIMA: "Axetilcefuroxima",
    AZITROMICINA: "Azitromicina",
    AZTREONAM: "Aztreonam",
    BACITRACINA: "Bacitracina",
    BRODIMOPRIMA: "Brodimoprima",
    CAPREOMICINA: "Capreomicina",
    CARBENICILINA: "Carbenicilina",
    CEFACLOR: "Cefaclor",
    CEFADROXIL: "Cefadroxil",
    CEFALEXINA: "Cefalexina",
    CEFALOTINA: "Cefalotina",
    CEFAZOLINA: "Cefazolina",
    CEFEPIMA: "Cefepima",
    CEFODIZIMA: "Cefodizima",
    CEFOPERAZONA: "Cefoperazona",
    CEFOTAXIMA: "Cefotaxima",
    CEFOXITINA: "Cefoxitina",
    CEFPIROMA: "Cefpiroma",
    CEFPODOXIMA: "Cefpodoxima",
    CEFPROZIL: "Cefprozil",
    CEFTADIZIMA: "Ceftadizima",
    CEFTRIAXONA: "Ceftriaxona",
    CEFUROXIMA: "Cefuroxima",
    CIPROFLOXACINA: "Ciprofloxacina",
    CLARITROMICINA: "Claritromicina",
    CLINDAMICINA: "Clindamicina",
    CLOFAZIMINA: "Clofazimina",
    CLORANFENICOL: "Cloranfenicol",
    CLOXACILINA: "Cloxacilina",
    DAPSONA: "Dapsona",
    DAPTOMICINA: "Daptomicina",
    DICLOXACILINA: "Dicloxacilina",
    DIFENILSULFONA: "Difenilsulfona",
    DIIDROESTREPTOMICINA: "Diidroestreptomicina",
    DIRITROMICINA: "Diritromicina",
    DORIPENEM: "Doripenem",
    DOXICICLINA: "Doxiciclina",
    ERITROMICINA: "Eritromicina",
    ERTAPENEM: "Ertapenem",
    ESPECTINOMICINA: "Espectinomicina",
    ESPIRAMICINA: "Espiramicina",
    ESTREPTOMICINA: "Estreptomicina",
    ETAMBUTOL: "Etambutol",
    ETIONAMIDA: "Etionamida",
    FOSFOMICINA: "Fosfomicina",
    FTALILSULFATIAZOL: "Ftalilsulfatiazol",
    GATIFLOXACINA: "Gatifloxacina",
    GEMIFLOXACINO: "Gemifloxacino",
    GENTAMICINA: "Gentamicina",
    IMIPENEM: "Imipenem",
    ISONIAZIDA: "Isoniazida",
    LEVOFLOXACINA: "Levofloxacina",
    LIMECICLINA: "Limeciclina",
    LINCOMICINA: "Lincomicina",
    LINEZOLIDA: "Linezolida",
    LOMEFLOXACINA: "Lomefloxacina",
    LORACARBEF: "Loracarbef",
    MANDELAMINA: "Mandelamina",
    MEROPENEM: "Meropenem",
    METAMPICILINA: "Metampicilina",
    METRONIDAZOL: "Metronidazol",
    MINOCICLINA: "Minociclina",
    MIOCAMICINA: "Miocamicina",
    MOXIFLOXACINO: "Moxifloxacino",
    MUPIROCINA: "Mupirocina",
    NEOMICINA: "Neomicina",
    NETILMICINA: "Netilmicina",
    NITROFURANTOINA: "Nitrofurantoína",
    NITROXOLINA: "Nitroxolina",
    NORFLOXACINA: "Norfloxacina",
    OFLOXACINA: "Ofloxacina",
    OXACILINA: "Oxacilina",
    OXITETRACICLINA: "Oxitetraciclina",
    PEFLOXACINA: "Pefloxacina",
    PENICILINA_G: "Penicilina G",
    PENICILINA_V: "Penicilina V",
    PIPERACILINA: "Piperacilina",
    PIRAZINAMIDA: "Pirazinamida",
    POLIMIXINA_B: "Polimixina B",
    PRISTINAMICINA: "Pristinamicina",
    PROTIONAMIDA: "Protionamida",
    RETAPAMULINA: "Retapamulina",
    RIFAMICINA: "Rifamicina",
    RIFAMPICINA: "Rifampicina",
    RIFAPENTINA: "Rifapentina",
    ROSOXACINA: "Rosoxacina",
    ROXITROMICINA: "Roxitromicina",
    SULBACTAM: "Sulbactam",
    SULFADIAZINA: "Sulfadiazina",
    SULFADOXINA: "Sulfadoxina",
    SULFAGUANIDINA: "Sulfaguanidina",
    SULFAMERAZINA: "Sulfamerazina",
    SULFAMETIZOL: "Sulfametizol",
    SULFAMETOXAZOL: "Sulfametoxazol",
    SULFAMETOXIPIRIDAZINA: "Sulfametoxipiridazina",
    SULFAMETOXIPIRIMIDINA: "Sulfametoxipirimidina",
    SULFANILAMIDA: "Sulfanilamida",
    SULFATIAZOL: "Sulfatiazol",
    SULTAMICILINA: "Sultamicilina",
    TAZOBACTAM: "Tazobactam",
    TEICOPLANINA: "Teicoplanina",
    TELITROMICINA: "Telitromicina",
    TETRACICLINA: "Tetraciclina",
    TIANFENICOL: "Tianfenicol",
    TICARCILINA: "Ticarcilina",
    TIGECICLINA: "Tigeciclina",
    TIROTRICINA: "Tirotricina",
    TOBRAMICINA: "Tobramicina",
    TRIMETOPRIMA: "Trimetoprima",
    TROVAFLOXACINA: "Trovafloxacina",
    VANCOMICINA: "Vancomicina"
};

export default Antibiotico;
