const Cidade = {
    ABAIARA: "Abaiara",
    ACOPIARA: "Acopiara",
    ACARAPE: "Acarape",
    ACARAU: "Acarau",
    AIUABA: "Aiuaba",
    ALENQUER: "Alenquer",
    ALTO_SANTO: "Alto Santo",
    ALTANEIRA: "Altaneira",
    AMARAJI: "Amaraji",
    AMONTADA: "Amontada",
    ANTONINA_DO_NORTE: "Antonina do Norte",
    APUIARES: "Apuiarés",
    ARACATI: "Aracati",
    ARARENDÁ: "Ararendá",
    ASSARE: "Assaré",
    AURORA: "Aurora",
    BAIXIO: "Baixio",
    BARBALHA: "Barbalha",
    BARRO: "Barro",
    BARROQUINHA: "Barroquinha",
    BATURITE: "Baturité",
    BEBERIBE: "Beberibe",
    BELA_CRUZ: "Bela Cruz",
    BOA_VIAGEM: "Boa Viagem",
    BREJO_SANTO: "Brejo Santo",
    CAMOCIM: "Camocim",
    CAMPOS_SALES: "Campos Sales",
    CARIRIAÇU: "Caririaçu",
    CARNAUBAL: "Carnaubal",
    CATERINA: "Catarina",
    CAUCAIA: "Caucaia",
    CEDRO: "Cedro",
    CHAVAL: "Chaval",
    CHORO: "Choró",
    COREAU: "Coreau",
    CRATEUS: "Crateús",
    CRATO: "Crato",
    CROATA: "Croatá",
    DEPUTADO_IRAPUAN_PINHEIRO: "Deputado Irapuan Pinheiro",
    ERERE: "Ererê",
    EUSEBIO: "Eusébio",
    FARIAS_BRITO: "Farias Brito",
    FORTALEZA: "Fortaleza",
    FRECHEIRINHA: "Frecheirinha",
    GUAIUBA: "Guaiúba",
    ICO: "Icó",
    ICAPUI: "Icapuí",
    IBIAPINA: "Ibiapina",
    IBATETAMA: "Ibaretama",
    IPU: "Ipu",
    IPUEIRAS: "Ipueiras",
    ITAITINGA: "Itaitinga",
    ITAPAGE: "Itapagé",
    ITAPIPOCA: "Itapipoca",
    ITAREMA: "Itarema",
    JAGUARETAMA: "Jaguaretama",
    JAGUARIBE: "Jaguaribe",
    JAGUARUANA: "Jaguaruana",
    JARDIM: "Jardim",
    JATI: "Jati",
    JICOCA_DE_JERICOACOARA: "Jijoca de Jericoacoara",
    JUCAS: "Jucás",
    LAVRAS_DA_MANGABEIRA: "Lavras da Mangabeira",
    LIMOEIRO_DO_NORTE: "Limoeiro do Norte",
    MARACANAU: "Maracanaú",
    MARANGUAPE: "Maranguape",
    MARCO: "Marco",
    MASSAPE: "Massapê",
    MAURITI: "Mauriti",
    MERUOCA: "Meruoca",
    MILAGRES: "Milagres",
    MILHA: "Milhã",
    MIRAIMA: "Miraíma",
    MISSAO_VELHA: "Missão Velha",
    MOMBAÇA: "Mombaça",
    MONSENHOR_TABOSA: "Monsenhor Tabosa",
    MORADA_NOVA: "Morada Nova",
    MUCAMBO: "Mucambo",
    MULUNGU: "Mulungú",
    NOVA_OLINDA: "Nova Olinda",
    NOVA_RUSSAS: "Nova Russas",
    NOVO_ORIENTE: "Novo Oriente",
    OCARA: "Ocara",
    OROS: "Orós",
    PACAJUS: "Pacajus",
    PACATUBA: "Pacatuba",
    PARACURU: "Paracuru",
    PARAIPABA: "Paraipaba",
    PARAMBU: "Parambu",
    PEDRA_BRANCA: "Pedra Branca",
    PIQUET_CARNEIRO: "Piquet Carneiro",
    PORANGA: "Poranga",
    QUIXADA: "Quixadá",
    QUIXERAMOBIM: "Quixeramobim",
    QUIXERE: "Quixeré",
    REDECAO: "Redenção",
    RUSSAS: "Russas",
    SANTA_QUITERIA: "Santa Quitéria",
    SANTANA_DO_CARIRI: "Santana do Cariri",
    SAO_BENEDITO: "São Benedito",
    SAO_JOAO_DO_JAGUARIBE: "São João do Jaguaribe",
    SAO_LUIS_DO_CURU: "São Luís do Curu",
    SAO_MATEUS: "São Mateus",
    SAO_RAIMUNDO_NONATO: "São Raimundo Nonato",
    SENADOR_POMPEU: "Senador Pompeu",
    SOLONOPOLE: "Solonópole",
    SOBRAL: "Sobral",
    TAUA: "Tauá",
    TEJUCUOCA: "Tejuçuoca",
    TIANGUA: "Tianguá",
    UMARI: "Umari",
    UMIRIM: "Umirim",
    URUBURETAMA: "Uruburetama",
    VARZEA_ALEGRE: "Várzea Alegre",
    VICOSA_DO_CEARA: "Viçosa do Ceará"
};

export default Cidade;