const Convenio = {
    HAPVIDA: "Hapvida",
    IPM: "IPM",
    ISSEC: "ISSEC",
    SUS: "Sus",
    UNIMED: "Unimed",
    OUTROS: "Outros",
    SI: "SI"
  };
  
  const PlanejamentoDeGestacao = {
    PLANEJADA: "Planejada",
    NAO_PLANEJADA_ACEITA: "Não planejada, mas aceita",
    NAO_PLANEJADA_DESEJADA: "Não planejada, mas desejada",
    INDESEJADA: "Indesejada",
    REJEITADA: "Rejeitada",
    SI: "SI"
  };
  
  const ContraceptiveMethods = {
    ANTICONCEPCIONAL_INJETAVEL_MENSAL: "Anticoncepcional Injetável - Mensal",
    ANTICONCEPCIONAL_INJETAVEL_TRIMESTRAL: "Anticoncepcional Injetável - Trimestral",
    ANTICONCEPCIONAL_ORAL: "Anticoncepcional oral",
    COITO_INTERROMPIDO: "Coito interrompido",
    DIU: "DIU",
    METODO_TABELA: "Método tabela",
    PRESERVATIVO: "Preservativo",
    NENHUM: "Nenhum",
    OUTROS: "Outros",
    SI: "SI"
  };
  
  const MeioAbortivo = {
    ABORTO_MEDICAMENTOSO: "Aborto medicamentoso",
    CHAS: "Chás",
    CURETAGEM: "Curetagem",
    CYTOTEC: "Cytotec",
    METODO_ASPIRACAO: "Método de aspiração",
    OUTROS: "Outros",
    SI: "SI"
  };
  
  const ListSimOuNao = {
    SIM: "Sim",
    NAO: "Não",
    SI: "SI"
  };
  
  const IntercorrenciasGestacao = {
    ACIDENTE: "Acidente",
    ANEMIA: "Anemia",
    CARDIOPATIA: "Cardiopatia",
    DEPRESSAO: "Depressão",
    DIABETES_GESTACIONAL: "Diabetes gestacional",
    DOENCA_AUTOIMUNE: "Doença autoimune",
    HIPEREMESE: "Hiperêmese",
    HIPOTIREOIDISMO: "Hipotireoidismo",
    SINDROME_HELLP: "Sídrome de HELLP",
    SINDROMES_HIPERTENSIVAS_GESTACAO: "Síndromes hipertensivas na gestação",
    TRANSTORNO_PSIQUICO: "Transtorno psíquico",
    TRATAMENTO_PSIQUIATRICO: "Tratamento psiquiátrico",
    OUTROS: "Outros",
    SI: "SI"
  };

  const Alergias = {
    ASMA: "Asma",
    APARELHO_RESPIRATORIO: "Aparelho Respiratório",
    MEDICAMENTOSAS: "Medicamentosas",
    OCULARES: "Oculares",
    PELE: "Pele",
    SISTEMICA_ALIMENTAR: "Sistêmica / alimentar",
    RINITE: "Rinite",
    NENHUMA: "Nenhuma",
    OUTROS: "Outros",
    SI: "SI"
  };

  const Infeccoes = {
    CANCRO_MOLE: "Cancro mole (cancroide)",
    CHIKUNGUNHA: "Chikungunha",
    CITOMEGALOVIROSE: "Citomegalovirose",
    COVID: "Covid",
    DENGUE: "Dengue",
    DOENCA_INFLAMATORIA_PELVICA: "Doença Inflamatória Pélvica (DIP)",
    DONOVANOSE: "Donovanose",
    GONORREIA: "Gonorreia",
    HEPATITE_B_C: "Hepatite B e C",
    HERPES_GENITAL: "Herpes genital",
    HIV_AIDS: "HIV/AIDS",
    HPV: "HPV",
    INFECCAO_TRATO_URINARIO: "Infecção do trato urinário",
    INFECCAO_HTLV: "Infecção pelo HTLV",
    INFECCAO_CLAMIDIA: "Infecção por Clamídia",
    LINFOGRANULOMA_VENEREO: "Linfogranuloma venéreo (LGV)",
    RESFRIADO: "Resfriado",
    RUBEOLA: "Rubéola",
    SIFILIS: "Sífilis",
    TOXOPLASMOSE: "Toxoplasmose",
    TRICOMONIASE: "Tricomoníase",
    ZIKA: "Zika",
    NENHUMA: "Nenhuma",
    OUTROS: "Outros",
    SI: "SI"
  };

  const DoencasPreExistentesMae = {
    ALERGIA_ALIMENTAR: "Alergia alimentar",
    ALERGIA_MEDICAMENTOSA: "Alergia medicamentosa",
    ALERGIA_OCULAR: "Alergia ocular",
    ASMA_ALERGICA: "Asma alérgica",
    DERMATITE_ALERGICA: "Dermatite alérgica",
    RINITE_ALERGICA: "Rinite alérgica",
    
    AUTOIMUNE_ANEMIA_HEMOLITICA: "Autoimune - Anemia hemolítica",
    AUTOIMUNE_ARTRITE_REUMATOIDE: "Autoimune - Artrite reumatóide",
    AUTOIMUNE_DIABETES_TIPO_1: "Autoimune - Diabetes tipo 1",
    AUTOIMUNE_DOENCA_CELIACA: "Autoimune - Doença celíaca",
    AUTOIMUNE_ESCLEROSE_MULTIPLA: "Autoimune - Esclerose múltipla",
    AUTOIMUNE_LUPUS: "Autoimune - Lupus eritematoso sistêmico",
    AUTOIMUNE_SJOGREN: "Autoimune - Síndrome de Sjögren",
    AUTOIMUNE_HASHIMOTO: "Autoimune - Tireóide de Hashimoto",
    AUTOIMUNE_VITILIGO: "Autoimune - Vitiligo",
    
    CARDIOPATIA_ANGINA: "Cardiopatias - Angina",
    CARDIOPATIA_ANOMALIA_EBSTEIN: "Cardiopatias - Anomalia de Ebstein",
    CARDIOPATIA_ARRITMIA: "Cardiopatias - Arritmia",
    CARDIOPATIA_ATRESIA_PULMONAR: "Cardiopatias - Atresia pulmonar",
    CARDIOPATIA_COMUNICACAO_INTERATRIAL: "Cardiopatias - Comunicação interatrial",
    CARDIOPATIA_COMUNICACAO_INTERVENTRICULAR: "Cardiopatias - Comunicação interventricular",
    CARDIOPATIA_DEFEITO_SEPTO_ATRIOVENTRICULAR: "Cardiopatias - Defeito no septo atrioventricular",
    CARDIOPATIA_ENDOCARDITE: "Cardiopatias - Encocardite",
    CARDIOPATIA_INFARTO: "Cardiopatias - Infarto",
    CARDIOPATIA_INSUFICIENCIA_CARDIACA: "Cardiopatias - Insuficiência cardíaca",
    CARDIOPATIA_MIOCARDITE: "Cardiopatias - Miocardite",
    CARDIOPATIA_PERICARDITE: "Cardiopatias - Pericardite",
    CARDIOPATIA_PERSISTENCIA_CANAL_ARTERIAL: "Cardiopatias - Persistência do canal arterial",
    CARDIOPATIA_TETRALOGIA_FALLOT: "Cardiopatias - tetralogia de Fallot",
    CARDIOPATIA_TRANSPOSICAO_GRANDES_VASOS: "Cardiopatias - transposição dos grandes vasos da base",
    CARDIOPATIA_VALVULOPATIA: "Cardiopatias - valvulopatia",
    
    DISTURBIO_COAGULACAO_CID: "Distúrbio de coagulação - Coagulação intravascular disseminada",
    DISTURBIO_COAGULACAO_DEFICIENCIA_ALFA2: "Distúrbio de coagulação - Deficiência de alfa 2-antiplasmina",
    DISTURBIO_COAGULACAO_DEFICIENCIA_FATOR_II: "Distúrbio de coagulação - Deficiência do fator II",
    DISTURBIO_COAGULACAO_DEFICIENCIA_FATOR_V: "Distúrbio de coagulação - Deficiência do fator V",
    DISTURBIO_COAGULACAO_DEFICIENCIA_FATOR_VII: "Distúrbio de coagulação - Deficiência do fator VII",
    DISTURBIO_COAGULACAO_DEFICIENCIA_FATOR_X: "Distúrbio de coagulação - Deficiência do fator X",
    DISTURBIO_COAGULACAO_DEFICIENCIA_FATOR_XI: "Distúrbio de coagulação - Deficiência do fator XI",
    DISTURBIO_COAGULACAO_HEMOFILIA: "Distúrbio de coagulação - Hemofilia / Doença de von Willebrand",
    DISTURBIO_COAGULACAO_TROMBOCITOPENIA: "Distúrbio de coagulação - Trombocitopenia",
    
    DOENCA_PSIQUIATRICA_ESQUIZOFRENIA: "Doenças psiquiátricas - Esquizofrenia",
    DOENCA_PSIQUIATRICA_PSICOSE_MANIACO_DEPRESSIVA: "Doenças psiquiátricas - Psicose maníaco depressiva",
    DOENCA_PSIQUIATRICA_PSICOSE_OBSESSIVA_COMPULSIVA: "Doenças psiquiátricas - Psicose obsessiva compulsiva",
    DOENCA_PSIQUIATRICA_BORDERLINE: "Doenças psiquiátricas - Transtorno borderline",
    DOENCA_PSIQUIATRICA_ANSIEDADE_GENERALIZADA: "Doenças psiquiátricas - Transtorno de ansiedade generalizada",
    DOENCA_PSIQUIATRICA_DISSOCIATIVO: "Doenças psiquiátricas - Transtorno dissociativo",
    DOENCA_PSIQUIATRICA_PANICO: "Doenças psiquiátricas - Transtorno do pânico",
    
    NENHUMA: "Nenhuma",
    OUTROS: "Outros",
    SI: "SI"
  };

  const UsoDrogasMae = {
    ALCOOL_1_4: "Álcool - 1 a 4 vezes por semana",
    ALCOOL_5_10: "Álcool - 5 a 10 vezes por semana",
    ALCOOL_11_20: "Álcool - 11 a 20 vezes por semana",
    ALCOOL_20_MAIS: "Álcool - Mais de 20 vezes",
    
    COCAINA_1_4: "Cocaína - 1 a 4 vezes por semana",
    COCAINA_5_10: "Cocaína - 5 a 10 vezes por semana",
    COCAINA_11_20: "Cocaína - 11 a 20 vezes por semana",
    COCAINA_20_MAIS: "Cocaína - Mais de 20 vezes",
    
    CRACK_1_4: "Crack - 1 a 4 vezes por semana",
    CRACK_5_10: "Crack - 5 a 10 vezes por semana",
    CRACK_11_20: "Crack - 11 a 20 vezes por semana",
    CRACK_20_MAIS: "Crack - Mais de 20 vezes",
    
    FUMO_1_10: "Fumo - 1 a 10 unidades por semana",
    FUMO_11_20: "Fumo - 11 a 20 unidades por semana",
    FUMO_20_MAIS: "Fumo - Mais de 20 unidades por semana",
    
    MACONHA_1_4: "Maconha - 1 a 4 vezes por semana",
    MACONHA_5_10: "Maconha - 5 a 10 vezes por semana",
    MACONHA_11_20: "Maconha - 11 a 20 vezes por semana",
    MACONHA_20_MAIS: "Maconha - Mais de 20 vezes",
    
    NENHUMA: "Nenhuma",
    OUTROS: "Outros",
    SI: "SI"
  };

  const ExamesRealizadosMae = {
    AMNIOCENTESE_ALTERADO: "Amniocentese - Alterado",
    AMNIOCENTESE_NORMAL: "Amniocentese - Normal",
    BIOPSIA_CARIOTIPO_FETAL_ALTERADO: "Biópsia cariótipo fetal - Alterado",
    BIOPSIA_CARIOTIPO_FETAL_NORMAL: "Biópsia cariótipo fetal - Normal",
    BIOPSIA_VILO_CORIAL_ALTERADO: "Biópsia do vilo corial - Alterado",
    BIOPSIA_VILO_CORIAL_NORMAL: "Biópsia do vilo corial - Normal",
    CARDIOTOCOGRAFIA_ALTERADO: "Cardiotocografia - Alterado",
    CARDIOTOCOGRAFIA_NORMAL: "Cardiotocografia - Normal",
    CORDOCENTESE_ALTERADO: "Cordocentese - Alterado",
    CORDOCENTESE_NORMAL: "Cordocentese - Normal",
    ECOCARDIOGRAMA_FETAL_NORMAL: "Ecocardiograma fetal - Normal",
    ELETROCARDIOGRAMA_FETAL_ALTERADO: "Eletrocardiograma fetal - Alterado",
    GLICOSE_JEJUM_ALTERADO: "Glicose em jejum - Alterado",
    GLICOSE_JEJUM_NORMAL: "Glicose em jejum - Normal",
    HEMOGRAMA_ALTERADO: "Hemograma - Alterado",
    HEMOGRAMA_NORMAL: "Hemograma - Normal",
    HIV_ALTERADO: "HIV - Alterado",
    HIV_NORMAL: "HIV - Normal",
    MAPA_ALTERADO: "MAPA - Alterado",
    MAPA_NORMAL: "MAPA - Normal",
    PERFIL_BIOQUIMICO_FETAL_ALTERADO: "Perfil bioquímico fetal - Alterado",
    PERFIL_BIOQUIMICO_FETAL_NORMAL: "Perfil bioquímico fetal - Normal",
    TIPO_SANGUINEO_FATOR_RH_ALTERADO: "Tipo sanguíneo e fator RH - Alterado",
    TIPO_SANGUINEO_FATOR_RH_NORMAL: "Tipo sanguíneo e fator RH - Normal",
    TORCH_ALTERADO: "TORCH - Alterado",
    TORCH_NORMAL: "TORCH - Normal",
    VDRL_ALTERADO: "VDRL - Alterado",
    VDRL_NORMAL: "VDRL - Normal",
    NENHUM: "Nenhum",
    OUTROS: "Outros",
    SI: "SI"
  };

  const MedicamentosUtilizadosMae = {
    ACIDO_FOLICO: "Ácido fólico",
    FERRO: "Ferro",
    VITAMINAS: "Vitaminas",
    ANTIEMETICOS: "Antieméticos",
    ANTIBIOTICOS: "Antibióticos",
    ANALGESICOS: "Analgésicos",
    ANTIABORTIVOS: "Antiabortivos",
    
    ANTI_HIPERTENSIVO_ADALAT: "Anti hipertensivo - Adalat",
    ANTI_HIPERTENSIVO_ALDACTONE: "Anti hipertensivo - Aldactone",
    ANTI_HIPERTENSIVO_ATENOLOL: "Anti hipertensivo - Atenelol",
    ANTI_HIPERTENSIVO_BESILATO_ANLODIPINO: "Anti hipertensivo - Besilato de Anlodipino",
    ANTI_HIPERTENSIVO_CAPTOPRIL: "Anti hipertensivo - Captopril",
    ANTI_HIPERTENSIVO_CARVEDILOL: "Anti hipertensivo - Carvedilol",
    ANTI_HIPERTENSIVO_DIURESS: "Anti hipertensivo - Diuress",
    ANTI_HIPERTENSIVO_ENALAPRIL: "Anti hipertensivo - Enalapril",
    ANTI_HIPERTENSIVO_ENTRESTO: "Anti hipertensivo - Entresto",
    ANTI_HIPERTENSIVO_ESPIRONOLACTONA: "Anti hipertensivo - Espironolactona",
    ANTI_HIPERTENSIVO_FUROSEMIDA: "Anti hipertensivo - Furosemida",
    ANTI_HIPERTENSIVO_HIDROCLOROTIAZIDA: "Anti hipertensivo - Hidroclorotiazida",
    ANTI_HIPERTENSIVO_HIDROCLOROTIZIDA: "Anti hipertensivo - Hidroclorotizida",
    ANTI_HIPERTENSIVO_LASIX: "Anti hipertensivo - Lasix",
    ANTI_HIPERTENSIVO_LOSARTANA: "Anti hipertensivo - Losartana",
    ANTI_HIPERTENSIVO_METILDOPA: "Anti hipertensivo - Metildopa",
    ANTI_HIPERTENSIVO_NIFEDIPINA: "Anti hipertensivo - Nifedipina",
    ANTI_HIPERTENSIVO_SELOKEN: "Anti hipertensivo - Seloken",
    ANTI_HIPERTENSIVO_VALSARTANA: "Anti hipertensivo - Valsartana",
    ANTI_HIPERTENSIVO_VASOPRIL: "Anti hipertensivo - Vasopril",
    
    PSICOTROPICOS: "Psicotrópicos",
    NENHUMA: "Nenhuma",
    OUTROS: "Outros",
    SI: "SI"
  };

  const Diagnostico = {
    COLELITIASE: "Colelitíase",
    DIABETES_MELLITUS: "Diabetes mellitus",
    DOENCAS_AUTOIMUNES: "Doenças autoimunes",
    DOENCAS_HEMATOLOGICAS: "Doenças hematológicas",
    HIPERTENSAO_ARTERIAL_CRONICA: "Hipertensão arterial crônica",
    HIPERTIREOIDISMO: "Hipertireoidismo",
    HIPOTIREOIDISMO: "Hipotireoidismo",
    NENHUM: "Nenhum",
    OLIGOIDRAMNIO: "Oligoidrâmnio",
    PLACENTA_ACRETA: "Placenta acreta/acretismo placentário",
    PLACENTA_PREVIA: "Placenta prévia",
    POLIDRAMNIO: "Polidrâmnio",
    TROMBOEMBOLISMO: "Tromboembolismo",
    OUTRO: "Outro",
    SI: "SI"
  };
  
  const MotivoHospitalizacao = {
    ACIDENTE_TRABALHO_MATERIAL_BIOLOGICO: "Acidente de trabalho com exposição a material biológico",
    ACIDENTE_ANIMAL_PECONHENTO: "Acidente por animal peçonhento",
    ACIDENTE_ANIMAL_RAIVA: "Acidente por animal potencialmente transmissor da raiva",
    ALOIMUNIZACAO: "Aloimunização",
    AMNIORREXE_PREMATURA: "Amniorrexe prematura",
    ANEMIA: "Anemia",
    ANTRAZ: "Antraz",
    APENDICITE: "Apendicite",
    ARTRITE_TAKAYASU: "Artrite de Takayasu",
    ARTRITE_REUMATOIDE: "Artrite reumatoide",
    ARTROSE_GENERALIZADA_SEVERA: "Artrose Generalizada Severa",
    ASMA: "Asma",
    ATELECTASIA: "Atelectasia",
    BOTULISMO: "Botulismo",
    BRONQUITE: "Bronquite",
    CANCER_TIREOIDE: "Câncer da tireoide",
    CANCER_TUBA_UTERINA: "Câncer da tuba uterina",
    CANCER_COLO_UTERO: "Câncer de colo de útero",
    CANCER_MAMA: "Câncer de mama",
    CANCER_VAGINA: "Câncer de vagina",
    CANCER_VULVA: "Câncer de vulva",
    CANCER_ENDOMETRIO: "Câncer do endométrio",
    CANCER_OVARIO: "Câncer do ovário",
    CARDIOPATIA: "Cardiopatia",
    CATAPORA: "Catapora",
    CHIKUNGUNYA: "Chikungunha",
    CISTOCELE: "Cistocele",
    CONVULSAO: "Convulsão",
    DENGUE: "Dengue",
    DIABETES_INSIPIDUS: "Diabetes insipidus",
    DIABETES_GESTACIONAL: "Diabetes mellitus gestacional (DMG)",
    DISTONIA_SEGMENTADA: "Distonia segmentada",
    DISTURBIOS_TIREOIDE: "Distúrbios da tireoide",
    DOENCA_AUTOIMUNE: "Doença auto imune",
    DOENCA_CHAGAS: "Doença de Chagas",
    DOENCA_CHARCOT_MARIE_TOOTH: "Doença de Charcot-Marie-Tooth",
    DOENCA_CREUTZFELDT_JAKOB: "Doença de Creutzfeldt-Jakob (DCJ)",
    DOENCA_HUNTINGTON: "Doença de Huntington",
    DOENCA_HAEMOPHILUS_INFLUENZA: "Doença Invasiva por Haemophilus Influenza",
    DOENCA_MENINGOCOCICA: "Doença Meningocócica e outras meningites",
    ECLAMPSIA: "Eclâmpsia",
    EDEMA_PULMONAR: "Edema pulmonar",
    EMBOLIA_GASOSA: "Embolia gasosa",
    EMBOLIA_PULMONAR: "Embolia pulmonar",
    ENDOMETRIOSE: "Endometriose",
    EPILEPSIA: "Epilepsia",
    ESCLEROSE_MULTIPLA: "Esclerose múltipla",
    ESQUISTOSSOMOSE: "Esquistossomose",
    FEBRE_NILO: "Febre do Nilo Ocidental e outras arboviroses",
    FEBRE_MACULOSA: "Febre Maculosa e outras Riquetisioses",
    FEBRE_TIFOIDE: "Febre tifoide",
    FRATURA: "Fratura",
    GASTRITE: "Gastrite",
    GLIOMA: "Glioma",
    HANSENIASE: "Hanseníase",
    HANTAVIROSE: "Hantavirose",
    HEMOFILIA: "Hemofilia",
    HEMORRAGIAS_GESTACAO: "Hemorragias da gestação",
    HEMORROIDA: "Hemorroida",
    HEMOSSIDEROSE_PULMONAR: "Hemossiderose pulmonar",
    HEPATITE_A: "Hepatite A",
    HEPATITE_B: "Hepatite B",
    HEPATITE_C: "Hepatite C",
    HERPES: "Herpes",
    HERPES_GENITAL: "Herpes genital",
    HIPEREMESE: "Hiperêmese",
    HIPERTENSAO_CRONICA: "Hipertensão crônica",
    HIPERTENSAO_GESTACIONAL: "Hipertensão gestacional",
    HIPOTIREOIDISMO: "Hipotireoidismo",
    HIV_AIDS: "HIV/AIDS - Infecção pelo Vírus da Imunodeficiência Humana ou Síndrome da Imunodeficiência Adquirida",
    INFARTO_AGUDO_MIOCARDIO: "Infarto agudo do miocárdio",
    INFECCAO_HIV_GESTANTE: "Infecção pelo HIV em gestante, parturiente ou puérpera e Criança exposta ao risco de transmissão vertical do HIV",
    INFECCAO_URINARIA: "Infecção urinária",
    INFLUENZA: "Influenza humana produzida por novo subtipo viral",
    INSUFICIENCIA_ISTMO_CERVICAL: "Insuficiência istmo-cervical",
    INSUFICIENCIA_RENAL_AGUDA: "Insuficiência renal aguda",
    INSUFICIENCIA_RENAL_CRONICA: "Insuficiência renal crônica",
    INTOXICACAO_EXOGENA: "Intoxicação Exógena (por substâncias químicas, incluindo agrotóxicos, gases tóxicos e metais pesados)",
    LEISHMANIOSE_TEGUMENTAR: "Leishmaniose tegumentar americana",
    LEISHMANIOSE_VISCERAL: "Leishmaniose Visceral",
    LEPTOSPIROSE: "Leptospirose",
    LEUCEMIA: "Leucemia",
    LUPUS: "Lúpus eritematoso sistêmico",
    MALARIA_AMAZONICA: "Malária na região amazônica",
    MALARIA_EXTRA_AMAZONICA: "Malária na região extra-Amazônica",
    MELANOMA: "Melanoma",
    MENINGITE: "Meningite",
    NEFROPATIA: "Nefropatia",
    NEOPLASIA_TROFOBLASTICA: "Neoplasia trofoblástica gestacional",
    PANCREATITE: "Pancreatite",
    PARKINSON: "Parkinson",
    PERIODONTITE: "Periodontite",
    PLACENTA_PREVIA: "Placenta prévia",
    PNEUMONIA: "Pneumonia",
    POLIOMIELITE: "Poliomielite",
    PRE_ECLAMPSIA: "Pré eclâmpsia",
    PROLAPSO_UTERINO: "Prolapso uterino",
    RAIVA: "Raiva",
    RETOCELE: "Retocele",
    RUBEOLA: "Rubéola e síndrome da rubéola congênita",
    SARAMPO: "Sarampo",
    SEPTICEMIA: "Septicemia",
    SIFILIS: "Sífilis",
    SINDROME_PFA: "Síndrome da Paralisia Flácida Aguda",
    SINDROME_GUILLAIN_BARRE: "Síndrome de Guillain Barré",
    SINDROME_HELLP: "Síndrome de HELLP",
    SINDROME_COVID: "Síndrome Respiratória Aguda Grave associada a Coronavírus",
    TETANO: "Tétano",
    TIREOIDE_HASHIMOTO: "Tireoide de Hashimoto",
    TOXOPLASMOSE: "Toxoplasmose gestacional e congênita",
    TROMBOEMBOLISMO: "Tromboembolismo",
    TROMBOFILIA: "Trombofilia",
    TUBERCULOSE: "Tuberculose",
    TULAREMIA: "Tularemia",
    UTEROCELE: "Uterocele",
    VAGINOSE_BACTERIANA: "Vaginose bacteriana",
    VARICELA: "Varicela",
    VARIOLA: "Varíola",
    VASCULOPATIA: "Vasculopatia",
    VIOLENCIA_DOMESTICA: "Violência doméstica e/ou outras violências",
    VIOLENCIA_SEXUAL: "Violência sexual e tentativa de suicídio",
    ZIKA: "Zika",
    OUTRO: "Outro",
    SI: "SI"
  };
  
  export { Convenio, PlanejamentoDeGestacao, ContraceptiveMethods, MeioAbortivo, ListSimOuNao, IntercorrenciasGestacao,MotivoHospitalizacao, Diagnostico, MedicamentosUtilizadosMae, ExamesRealizadosMae, UsoDrogasMae, DoencasPreExistentesMae, Infeccoes, Alergias};
  
  