const Estado = {
    ACRE: "Acre",
    AMAPA: "Amapá",
    AMAZONAS: "Amazonas",
    PARA: "Pará",
    RONDONIA: "Rondônia",
    RORAIMA: "Roraima",
    TOCATINS: "Tocantis",
    ALAGOAS: "Alagoas",
    BAHIA: "Bahia",
    CEARA: "Ceará",
    MARANHAO: "Maranhão",
    PARAIBA: "Paraíba",
    PERNAMBUCO: "Pernambuco",
    PIAUI: "Piauí",
    RIO_GRANDE_DO_NORTE: "Rio Grande do Norte",
    SERGIPE: "Sergipe",
    DISTRITO_FEDERAL: "Distrito Federal",
    GOIAS: "Goiás",
    MATO_GROSSO: "Mato Grosso",
    MATO_GROSSO_DO_SUL: "Mato Grosso do Sul",
    ESPIRITO_SANTO: "Espírito Santo",
    MINAS_GERAIS: "Minas Gerais",
    RIO_DE_JANEIRO: "Rio de Janeiro",
    SAO_PAULO: "São Paulo",
    PARANA: "Paraná",
    RIO_GRANDE_DO_SUL: "Rio Grande do Sul",
    SANTA_CATARINA: "Santa Catarina",
}

export default Estado;