const Intercorrencia = {
    ANEMIA: "Anemia",
    APNEIA: "Apneia",
    ASFIXIA: "Asfixia",
    CARDIOPATIA_ACIANOTICA_CIA: "Cardiopatia Acianótica – CIA",
    CARDIOPATIA_ACIANOTICA_CIV: "Cardiopatia Acianótica – CIV",
    CARDIOPATIA_ACIANOTICA_PCA: "Cardiopatia Acianótica – PCA",
    CARDIOPATIA_CIANOTICA_CORACAO_UNIVENTRICULAR: "Cardiopatia Cianótica – Coração univentricular",
    CARDIOPATIA_CIANOTICA_DRENAGEM_VEIAS_PULMONARES: "Cardiopatia Cianótica – Drenagem anômala total das veias pulmonares",
    CARDIOPATIA_CIANOTICA_ESTENOSE_AORTICA: "Cardiopatia Cianótica – Estenose aórtica",
    CARDIOPATIA_CIANOTICA_TETRALOGIA_FALLOT: "Cardiopatia Cianótica – Tetralogia de Fallot",
    CARDIOPATIA_CIANOTICA_TRANSPOSICAO_GRANDES_VASOS: "Cardiopatia Cianótica – Transposição dos grandes vasos da base",
    CARDIOPATIA_CIANOTICA_TRUNCUS_ARTERIOSUS: "Cardiopatia Cianótica – Truncus arteriosus",
    CITOMEGALOVIROSE: "Citomegalovirose",
    CONVULSAO: "Convulsão",
    COVID: "Covid",
    DISPLASIA_BRONCOPULMONAR: "Displasia broncopulmonar",
    DISTURBIOS_HIDROELETROLITICOS: "Distúrbios hidroeletrolíticos",
    ENTEROCOLITE_NECROZANTE: "Enterocolite necrozante",
    HEMORRAGIA_INTRACRANIANA_GRAU_I: "Hemorragia intracraniana – Grau I",
    HEMORRAGIA_INTRACRANIANA_GRAU_II: "Hemorragia intracraniana – Grau II",
    HEMORRAGIA_INTRACRANIANA_GRAU_III: "Hemorragia intracraniana – Grau III",
    HEMORRAGIA_INTRACRANIANA_GRAU_IV: "Hemorragia intracraniana – Grau IV",
    HERPES: "Herpes",
    HIDROCEFALIA: "Hidrocefalia",
    HIPERGLICEMIA: "Hiperglicemia",
    ICTERICIA: "Icterícia",
    INFECCAO_INTRAPARTO: "Infecção intraparto",
    INFECCAO_POS_PARTO: "Infecção pós parto",
    MENINGITE_NAO_ESPECIFICADA: "Meningite - não especificada",
    MENINGITE_BACTERIANA: "Meningite bacteriana",
    MENINGITE_FUNGICA: "Meningite fúngica",
    MENINGITE_VIRAL: "Meningite viral",
    MIELOMENINGOCELE_CORRECAO_POS_NASCIMENTO: "Mielomeningocele - Correção após o nascimento",
    MIELOMENINGOCELE_CORRECAO_INTRAUTERINA: "Mielomeningocele - Correção intrauterina",
    MICROFTALMIA_GLAUCOMA: "Microftalmia glaucoma",
    OSTEOGENESE_IMPERFEITA: "Osteogenese imperfeita",
    PCR_PARADA_CARDIORRESPIRATORIA: "PCR - Parada cardiorrespiratória",
    POLICITEMIA_PNEUMONITE: "Policitemia Pneumonite",
    RETROVIROSE: "Retrovirose",
    RUBEOLA: "Rubéola",
    SEPTICEMIA: "Septicemia",
    SIFILIS: "Sífilis",
    SINDROME_DE_WILLIAMS: "Síndrome de Williams",
    SINDROME_DESCONFORTO_RESPIRATORIO: "Síndrome do desconforto respiratório",
    SINDROME_HEMORRAGICA: "Síndrome hemorrágica",
    TOXOPLASMOSE: "Toxoplasmose",
    ZIKA: "Zika",
    NENHUMA: "Nenhuma",
    OUTROS: "Outros",
    SI: "SI"
};

export default Intercorrencia;
