const Malformacao = {
    ANENCEFALIA: "Anencefalia",
    ARTROGRIPOSE: "Artrogripose",
    ESTENOSE_CRANIOFACIAL: "Estenose craniofacial",
    FENDA_PALATINA: "Fenda palatina",
    HIDRANENCEFALIA: "Hidranencefalia",
    HIDROCEFALIA: "Hidrocefalia",
    LABIO_LEPORINO: "Lábio leporino",
    MIELOMENINGOCELE: "Mielomeningocele",
    PE_TORTO: "Pé torto",
    SINDROME_A_ESCLARECER: "Síndrome a esclarecer",
    SINDROME_DE_APERT: "Síndrome de Apert",
    SINDROME_DE_BECKWITH_WIEDEMANN: "Síndrome de Beckwith Wiedemann",
    SINDROME_DE_CRI_DU_CHAT: "Síndrome de Cri du Chat",
    SINDROME_DE_DOWN: "Síndrome de Down",
    SINDROME_DE_EDWARDS: "Síndrome de Edwards",
    SINDROME_DE_HUNTER: "Síndrome de Hunter",
    SINDROME_DE_KLINEFELTER: "Síndrome de Klinefelter",
    SINDROME_DE_MARFAN: "Síndrome de Marfan",
    SINDROME_DE_MOEBIUS: "Síndrome Mo\"e\"bius",
    SINDROME_DE_NOONAN: "Síndrome de Noonan",
    SINDROME_DE_ONDINE: "Síndrome de Ondine",
    SINDROME_DE_PIERRE_ROBIN: "Síndrome de Pierre Robin",
    SINDROME_DE_PRADER_WILLI: "Síndrome de Prader Willi",
    SINDROME_DE_PROTEU: "Síndrome de Proteu",
    SINDROME_DE_RETT: "Síndrome de Rett",
    SINDROME_DE_SANFILIPPO: "Síndrome de Sanfilippo",
    SINDROME_DE_TOURETTE: "Síndrome de Tourette",
    SINDROME_DE_TURNER: "Síndrome de Turner",
    SINDROME_DO_X_FRAGIL: "Síndrome do X Frágil",
    SINDROME_PATAU: "Síndrome Patau",
    OUTROS: "Outros"
};

export default Malformacao;
