const Naturalidade = {
    ACRE: "Acre - AC",
    AMAPA: "Amapá - AP",
    AMAZONAS: "Amazonas - AM",
    PARA: "Pará - PA",
    RONDONIA: "Rondônia - RO",
    RORAIMA: "Roraima - RR",
    TOCATINS: "Tocantis - TO",
    ALAGOAS: "Alagoas - AL",
    BAHIA: "Bahia - BA",
    CEARA: "Ceará - CE",
    MARANHAO: "Maranhão - MA",
    PARAIBA: "Paraíba - PB",
    PERNAMBUCO: "Pernambuco - PE",
    PIAUI: "Piauí - PI",
    RIO_GRANDE_DO_NORTE: "Rio Grande do Norte - RN",
    SERGIPE: "Sergipe - SE",
    DISTRITO_FEDERAL: "Distrito Federal - DF",
    GOIAS: "Goiás - GO",
    MATO_GROSSO: "Mato Grosso - MT",
    MATO_GROSSO_DO_SUL: "Mato Grosso do Sul - MS",
    ESPIRITO_SANTO: "Espírito Santo - ES",
    MINAS_GERAIS: "Minas Gerais - MG",
    RIO_DE_JANEIRO: "Rio de Janeiro - RJ",
    SAO_PAULO: "São Paulo - SP",
    PARANA: "Paraná - PR",
    RIO_GRANDE_DO_SUL: "Rio Grande do Sul - RS",
    SANTA_CATARINA: "Santa Catarina - SC",
}

export default Naturalidade;