const Ocupacao = {
    ADMINISTRADOR: "Administrador(a)",
    ADVOGADO: "Advogado(a)",
    AGENTE_VIAGENS: "Agente de viagens",
    AGRICULTOR: "Agricultor(a)",
    ANALISTA_SISTEMA: "Analista de sistema",
    ANALISTA_FINANCEIRO: "Analista financeiro",
    ARQUITETO: "Arquiteto(a)",
    ARTISTA_PLASTICO: "Artista plástico",
    ASSISTENTE_ADMINISTRATIVO: "Assistente administrativo",
    AGENTE_ADMINISTRATIVO: "Agente administrativo",
    ASSISTENTE_SOCIAL: "Assistente social",
    ATOR_ATRIZ: "Ator/Atriz",
    AUTONOMO: "Autônomo",
    BOMBEIRO: "Bombeiro(a)",
    CHEF_COZINHA: "Chef de cozinha",
    CIENTISTA_DADOS: "Cientista de dados",
    CONSULTOR_RH: "Consultor(a) de RH",
    CONTADOR: "Contador(a)",
    DENTISTA: "Dentista",
    DESIGNER: "Designer",
    DESIGNER_MODA: "Designer de moda",
    DO_LAR: "Do lar",
    ECONOMISTA: "Economista",
    ELETRICISTA: "Eletricista",
    ENCANADOR: "Encanador(a)",
    ENFERMEIRO: "Enfermeiro(a)",
    ENGENHEIRO: "Engenheiro(a)",
    FARMACEUTICO: "Farmacêutico(a)",
    FISIOTERAPEUTA: "Fisioterapeuta",
    GEOLOGO: "Geólogo",
    JORNALISTA: "Jornalista",
    JUIZ_PROMOTOR: "Juiz(a)/Promotor(a)",
    MEDICO_VETERINARIO: "Médico veterinário",
    MEDICO: "Médico(a)",
    MOTORISTA_ONIBUS_CAMINHAO: "Motorista de ônibus ou caminhão",
    MOTORISTA_APLICATIVO: "Motorista por aplicativo",
    MUSICO: "Músico",
    NUTRICIONISTA: "Nutricionista",
    OCEONOGRAFO: "Oceonógrafo",
    PEDREIRO: "Pedreiro",
    PINTOR: "Pintor",
    POLICIAL: "Policial",
    PORTEIRO: "Porteiro",
    PROFESSOR: "Professor(a)",
    PROGRAMADOR_COMPUTADOR: "Programador(a) de computador",
    PSICOLOGO: "Psicólogo(a)",
    PSIQUIATRA: "Psiquiatra",
    PUBLICITARIO: "Publicitário(a)",
    SECRETARIO: "Secretário(a)",
    SERVENTE: "Servente",
    TECNICO_AGRICOLA: "Técnico(a) agrícola",
    TECNICO_ELETRONICA: "Técnico(a) em eletrônica",
    TECNICO_ENFERMAGEM: "Técnico(a) em enfermagem",
    TECNICO_INFORMATICA: "Técnico(a) em informática",
    TECNICO_MECANICA: "Técnico(a) em mecânica",
    TECNICO_RADIOLOGIA: "Técnico(a) em radiologia",
    TECNICO_SEGURANCA_TRABALHO: "Técnico(a) em segurança do trabalho",
    TERAPEUTA_OCUPACIONAL: "Terapeuta ocupacional",
    TRADUTOR_INTEPRETE: "Tradutor(a)/intérprete",
    VETERINARIO: "Veterinário(a)",
    OUTRO: "Outro",
    SI: "SI"
};

export default Ocupacao;