const Terapeutica = {
    ADRENALINA: "Adrenalina",
    AMICACINA: "Amicacina",
    AMPICILINA: "Ampicilina",
    CAFEINA: "Cafeína",
    DIURETICOS_FUROSEMIDA: "Diuréticos furosemida",
    DIURETICOS_HIDROCLOROTIAZIDA: "Diuréticos hidroclorotiazida",
    EXSANGUINEO_TRANSFUSAO: "Exsanguíneo-transfusão",
    FLUCONAZOL: "Fluconazol",
    FOTOTERAPIA: "Fototerapia",
    GENTAMICINA: "Gentamicina",
    MEROPENEM: "Meropenem",
    OXIGENIOTERAPIA_CATETER: "Oxigenioterapia O2 sob cateter",
    OXIGENIOTERAPIA_HOOD: "Oxigenioterapia O2 sob Hood",
    PENICILINA_CRISTALINA: "Penicilina Cristalina",
    RIFAMPICINA: "Rifampicina",
    SUPORTE_VENTILATORIO_CPAP: "Suporte ventilatório não invasivo CPAP",
    SUPORTE_VENTILATORIO_VNI: "Suporte ventilatório não invasivo VNI",
    SURFACTANTE: "Surfactante",
    TAZOCIN: "Tazocin",
    TOBRAMICINA: "Tobramicina",
    TRANSFUSAO_PLAQUETAS: "Transfusão de plaquetas",
    TRANSFUSAO_PLASMA: "Transfusão de plasma",
    TRANSFUSAO_SANGUE: "Transfusão de sangue",
    VENTILACAO_MECANICA_1_SEMANA: "Ventilação mecânica-acima de 1 semana",
    VENTILACAO_MECANICA_15_DIAS: "Ventilação mecânica-acima de 15 dias",
    VENTILACAO_MECANICA_72_HORAS: "Ventilação mecânica-superior a 72 horas",
    OUTRO: "Outro",
    SI: "SI"
};

export default Terapeutica;
