const UF = {
    ACRE: "AC",
    AMAPA: "AP",
    AMAZONAS: "AM",
    PARA: "PA",
    RONDONIA: "RO",
    RORAIMA: "RR",
    TOCATINS: "TO",
    ALAGOAS: "AL",
    BAHIA: "BA",
    CEARA: "CE",
    MARANHAO: "MA",
    PARAIBA: "PB",
    PERNAMBUCO: "PE",
    PIAUI: "PI",
    RIO_GRANDE_DO_NORTE: "RN",
    SERGIPE: "SE",
    DISTRITO_FEDERAL: "DF",
    GOIAS: "GO",
    MATO_GROSSO: "MT",
    MATO_GROSSO_DO_SUL: "MS",
    ESPIRITO_SANTO: "ES",
    MINAS_GERAIS: "MG",
    RIO_DE_JANEIRO: "RJ",
    SAO_PAULO: "SP",
    PARANA: "PR",
    RIO_GRANDE_DO_SUL: "RS",
    SANTA_CATARINA: "SC",
}

export default UF;