const ServicoSocial = {
    paciente: {},
    configuracaoFamiliar: "",
    descricaoConfiguracaoFamiliar: "",
    situacaoConjugalPais: "",
    presencaDosPais: "",
    tipoAcolhimento: "",
    abrigo: "",
    descricaoAbrigo: "",
    banheiro: "",
    dvd: "",
    automovel: "",
    microOndas: "",
    lavaLoucas: "",
    motocicleta: "",
    freezer: "",
    secadoraRoupa: "",
    empregadosDomesticos: "",
    aguaEncanada: "",
    microcomputador: "",
    ruaPavimentada: "",
    geladeira: "",
    grauInstrucaoChefeFamilia: "",
    lavaRoupa: "",
    periodicidadeTerapia: "",
    descricaoPeriodicidadeTerapia: "",
    diasTurnoTerapia: "",
    tipoTerapia: "",
    situacaoAtualInstituicao: "",
    observacoes: ""
};

export default ServicoSocial;